

# Example override file for Qwen2.5-VL

model:
  seq_length: 4096

train:
  train_iters: 20
  global_batch_size: 8
  micro_batch_size: 1
  eval_iters: 5

optimizer:
  lr: 0.00025
  min_lr: 0.000025

scheduler:
  lr_warmup_iters: 10

checkpoint:
  # Directory to save to. If null, no checkpoint will be saved.
  save: null

dist:
  use_megatron_fsdp: false
  use_torch_fsdp2: false

logger:
  log_interval: 1

dataset:
  sequence_length: 4096

rng:
  seed: 42

ddp:
  grad_reduce_in_fp32: true


