

# Example override file for Nemotron Nano V2 VL

model:
  seq_length: 8192
  freeze_language_model: False
  freeze_vision_model: False
  freeze_vision_projection: False
  tensor_model_parallel_size: 8

train:
  train_iters: 300
  global_batch_size: 16
  micro_batch_size: 1
  eval_iters: 0

optimizer:
  lr: 2e-6
  min_lr: 2e-7

scheduler:
  lr_warmup_iters: 20

checkpoint:
  save_interval: 50

dist:
  use_megatron_fsdp: false
  use_torch_fsdp2: false

logger:
  log_interval: 1

dataset:
  sequence_length: 8192
  maker_name: make_llava_video_178k_dataset
  maker_kwargs:
    video_root_path: ???
    subsets:
    - 0_30_s_nextqa

rng:
  seed: 42

ddp:
  grad_reduce_in_fp32: true


