

# Example override file for Nemotron Nano V2 VL

model:
  seq_length: 4096
  freeze_language_model: False
  freeze_vision_model: False
  freeze_vision_projection: False

train:
  train_iters: 2000
  global_batch_size: 32
  micro_batch_size: 1
  eval_iters: 0

optimizer:
  lr: 2e-5
  min_lr: 2e-6

scheduler:
  lr_warmup_iters: 5

checkpoint:
  # Directory to save to. If null, no checkpoint will be saved.
  save: ???
  save_interval: 200

dist:
  use_megatron_fsdp: false
  use_torch_fsdp2: false

logger:
  log_interval: 1

dataset:
  sequence_length: 4096
  maker_name: make_raven_dataset

rng:
  seed: 42

ddp:
  grad_reduce_in_fp32: true


